### ISSUE TITLE
cannot get ejs to read a var from a js file

### ISSUE THREAD

**Issue by erikisaac** [den-wdi-2/project-2#17]
https://github.com/tj/ejs/issues/92

http://stackoverflow.com/questions/10777246/interweave-ejs-and-javascript-variables-inside-tags

The error:
ReferenceError: /Users/erikisaac/Desktop/GA Project 2 - Heroes of Shake-It-Speare/Heroes-of-Shake-It-Speare/views/playerPage.ejs:39
   37| <td>...</td>
   38| <% var x = "!!!!!!!!!!" %>
>> 39| <td>"<%= y %>"</td>
   40| </tr>
   41| </table>
   42| <button>Keep New Hero</button>

y is not defined

**Comment by ZebGirouard** [comment]
This was an issue of trying to render front-end code in EJS which is a server-rendered (back-end) templating tool.
