### ISSUE TITLE
Not able to successfully get image from API

### ISSUE THREAD

**Issue by gliechty** [den-wdi-2/project-2#26]
Still on the same issue. 

Tried this: http://stackoverflow.com/questions/9739946/load-one-random-flickr-image-append-to-div

...and this: http://docs.mashape.com/javascript

...but get a weird error (it's a bunch of symbols-- could be an unparsed image, but either way it's showing up as an error. 

Just want to get my name in line for this afternoon/evening.

**Comment by ZebGirouard** [comment]
Took a look at this.  Distinguishing between "req" (controller param) and "request" (node library) is tough here.  "req" is what's coming *in* and "request" is something that sends stuff *out*.  I'll circle back in a bit.

**Comment by ZebGirouard** [comment]
Finally got the image coming back, but it is in binary format.   This link will help:

http://stackoverflow.com/questions/14915058/how-to-display-binary-data-as-image-extjs-4
