### ISSUE TITLE
Connecting API Key to jQuery $.get command

### ISSUE THREAD

**Issue by micahwierenga** [den-wdi-2/project-2#3]
I've done a bit of reading and found that I cannot require an api key to the front-end, but not sure how to connect it to my $.get command so that I can display it my iframe.

http://stackoverflow.com/questions/31931614/require-is-not-defined-node-js

http://stackoverflow.com/questions/38343751/require-is-not-defined-nodejs

**Comment by ZebGirouard** [comment]
Seems like this logic has moved to the back end.  Great work, Micah!
