### ISSUE TITLE
My form submit isn't being heard on the front end.

### ISSUE THREAD

**Issue by GisellaBella** [den-wdi-2/project-2#5]
I'm not even getting a 'yo'
and yes i'm closing my document ready after..any other ideas?

$(document).ready(function() {

console.log ("app.js loaded");

$( "#location-form form" ).submit(function(event) {
alert("yo");
event.preventDefault();
var location = $(this).serialize();
console.log(location);
});

**Comment by ZebGirouard** [comment]
Still working on this, will circle back in a bit.

**Comment by ZebGirouard** [comment]
Gisella has moved on to another API-related issue, we'll circle back later.
